apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: bookmyshow-app

  template:
    metadata:
      labels:
        app: bookmyshow-app

    spec:
      containers:
      - name: bookmyshow-app
        image: IMAGE_NAME
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        env:
        - name: PORT
          value: "3000"
